### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by nanagitplus** [DEVSENSE/phptools-docs#41] opened 2019-08-20 10:40 UTC
[DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt](https://github.com/DEVSENSE/phptools-docs/files/3520066/DEVSENSE.phptools-vscode-unresponsive.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `phptools-vscode`
- Extension Version: `1.0.3774`
- OS Version: `Linux x64 4.15.0-55-generic`
- VSCode version: `1.38.0-insider`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jakubmisek** [comment] 2019-08-21 17:08
Thank you for the cpuprofile.  It looks like the load of the extension causes the CPU load but all caused by the vscode itself. We'll keep working on it.
![image](https://user-images.githubusercontent.com/842150/63452642-11b04e80-c447-11e9-8b8a-54da2f508530.png)

**Comment by jakubmisek** [comment] 2019-09-05 12:02
we have released an update - `1.0.3936` - which improves the CPU usage, closing the issue, please one a new issue if problems persist.

**Closed by jakubmisek** 2019-09-05 12:02 UTC
