### ISSUE TITLE
Named argument default causes improper formatting

### ISSUE THREAD

**Issue by godismyjudge95** [DEVSENSE/phptools-docs#408] opened 2023-10-01 02:08 UTC
Example function:
```php
function foo($label, $default = null) {
}
```

example function call:
```php
foo(
	label: 'bar',
	default: 'baz',
);
```

which then gets reformatted like so:
```php
foo(
	label: 'bar',
default
	: 'baz',
);
```

I would imagine there are many other keywords which I believe are valid named arguments but would cause the same issue.

**Comment by Miloslav** [comment] 2023-10-02 13:14
Thanks for reporting this.

I can confirm this one. Will be fixed.

I've tried it with several other keywords which can be passed as named argument, so far only `default` seems to be a problem.

**Comment by godismyjudge95** [comment] 2023-10-02 13:23
I think `case` and `break` might also not work.

**Comment by Miloslav** [comment] 2023-10-02 14:08
Thanks again for reporting this. We've fixed it and it will be available in the next pre-release.

**Closed by Miloslav** 2023-10-02 14:08 UTC
