### ISSUE TITLE
Peeking reference and highlighting

### ISSUE THREAD

**Issue by oojacoboo** [DEVSENSE/phptools-docs#288] opened 2023-02-17 01:12 UTC
Why is the text of the class being highlighted here?  I've tried other themes and it's doing it for all themes.  It's entirely undesirable since you can't read the class very well.  It's highlighting the entire class being referenced.

![image](https://user-images.githubusercontent.com/764664/219524283-1033e197-8f83-4ed1-90ea-8cfe1e6a2cff.png)

**Comment by jakubmisek** [comment] 2023-02-17 10:54
Thank you for reporting the issue.

For anyone reading it, the steps to repro the issue is to navigate to a class symbol using the context menu command `Peek` -> `Peek Definition`.

I agree it's completely undesirable. It's not by design - it's a bug. We'll fix it.

**Comment by jakubmisek** [comment] 2023-02-17 11:49
fixed in the pre-release version `1.30.12569`

thank you!

**Closed by jakubmisek** 2023-02-17 11:49 UTC
Labels: bug
