### ISSUE TITLE
Support for JetBrains\PhpStorm\Deprecated stub

### ISSUE THREAD

**Issue by Morgy93** [DEVSENSE/phptools-docs#507] opened 2024-03-04 15:59 UTC
Hello,

there's a https://github.com/JetBrains/phpstorm-stubs/ for deprecations.
Example:
```
    #[Deprecated(
        reason: 'Replaced by bar()',
        replacement: '%class%->bar(%parametersList%)',
    )]
    public function foo(whatever..): string
    {
        return $this->bar(whatever..);
    }
```

It would be awesome to have this deprecation messages supported in VSCode.

**Comment by Morgy93** [comment] 2024-03-05 13:03
> Thank you for the suggestion. I think we already do that, do you have an example?
> 
> ![image](https://private-user-images.githubusercontent.com/842150/310122507-5d242ab9-442f-467f-bc87-747ea2daf8bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDM2ODAsIm5iZiI6MTcwOTY0MzM4MCwicGF0aCI6Ii84NDIxNTAvMzEwMTIyNTA3LTVkMjQyYWI5LTQ0MmYtNDY3Zi1iYzg3LTc0N2VhMmRhZjhiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMjU2MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTZmM2FhOGU4ZmI2OGU4OWRlN2JiYWZhNGQ3YjRhZjc3OWRkMGI5YjI0YzEwNjBkNzM4NWI2M2NlODhjOTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9Ly4nx0rHBiNdPB2n59mwuUOMcyWRmewuxr2zT0qyyQ)

Interesting, it works if it is used in the same file.
But in my case, it is "imported" from a `/** @var Class $class */`
And `$class->foo()` does not show the deprecation, even though in the `Class` it is set.

I cannot share my code directly, since it is paid stuff, but I could re-create something similar if needed. 🤔

**Comment by jakubmisek** [comment] 2024-03-06 13:02
Thank you for the details.

I think it may be caused by an ambiguity - if there is more than one class `Class` in the workspace.

Looking into it ...

**Comment by jakubmisek** [comment] 2024-03-29 18:26
Fixed in the next update.
Thanks!

**Closed by jakubmisek** 2024-03-29 18:26 UTC

**Comment by Morgy93** [comment] 2024-04-03 05:25
Yes, it works, thanks. 🥳

**Comment by Morgy93** [comment] 2024-04-03 05:29
@jakubmisek I am wondering if you can strike through the method name in the suggestion dropdown as well.

![image](https://github.com/DEVSENSE/phptools-docs/assets/7961978/05df0fff-7a00-444a-a78b-59c24d198e99)
The `xHtml` is deprecated which you can see after using it only.

I'd create another issue if it is possible UI-wise.

**Comment by jakubmisek** [comment] 2024-04-06 15:36
Pre-release fixes strikethrough in completion list. We have also added setting `"php.completion.showDeprecated"` to hide/strikethrough/showNormally the deprecated items in completion list.
