### ISSUE TITLE
Connection to server is erroring. Shutting down server.

### ISSUE THREAD

**Issue by sergeycherepanov** [DEVSENSE/phptools-docs#160] opened 2022-09-22 12:49 UTC
The error appear too often. And the extension does not work. 

How to get more details about the issue?

**Comment by jakubmisek** [comment] 2022-09-22 15:44
Thank you for reporting the issue.

Please take a look at Output panel, the tab "PHP Language Server"
Or in console in Help/Toggle Developer Tools.

Thanks!

**Comment by jakubmisek** [comment] 2022-09-25 23:30
Hi Sergey,

May I ask you to look at the Output panel, tab "PHP language Server" - we'd like to fix it as soon as possible.
![image](https://user-images.githubusercontent.com/842150/192170426-f6542dfc-3e27-4c00-aacc-a799f3ddf348.png)

Thank you

**Comment by jakubmisek** [comment] 2022-09-28 14:08
> The error appear too often. And the extension does not work.
Hello @sergeycherepanov 

I have noticed, you are talking about the extension on open-vsx.org (not visual studio code marketplace)

Please note, that on open-vsx, we had only "web" version of the extension because of the limitations of open-vsx.

**Please try the latest pre-release (`v1.18`), which is the complete extension. **

**Comment by jakubmisek** [comment] 2022-09-29 14:25
hello @sergeycherepanov 

we have updated the extension on open-vsx.org - you should be able to install the regular version of PHP Tools from there (as a **pre-release**)

please let me know if it helped!

**Comment by jakubmisek** [comment] 2022-09-30 20:51
hi @sergeycherepanov 

we have released an update that fixes the issue on [**open-vsx**](https://open-vsx.org/extension/devsense/phptools-vscode) for your platform.

Please try;

**Comment by jakubmisek** [comment] 2022-10-04 07:05
@sergeycherepanov - the issue on Open-VSX has been fixed, please try so we can close the issue.

Thank you

**Comment by sergeycherepanov** [comment] 2022-10-05 08:43
@jakubmisek thanks, I tried to download the extension directly. It was work from time to time till update. Currently looks like it fixed. The main question about the way to get more details because without it does not possible to describe the issue.

**Comment by jakubmisek** [comment] 2022-10-05 08:47
thank you @sergeycherepanov for trying the update.

You can get the error details in Help - Toggle Developer Tools - Console:

![image](https://user-images.githubusercontent.com/842150/194019671-d1f013e4-7f61-4039-bb30-fb96c31f96d7.png)

I hope it helps. Please let me know if it happens again, we'll try to fix it.

**Comment by jakubmisek** [comment] 2022-10-10 18:35
@sergeycherepanov is everything working now?
I'd like to ask you to update the review at https://open-vsx.org/extension/devsense/phptools-vscode/reviews with actual review and not use it for reporting bugs.
Thank you

**Comment by jakubmisek** [comment] 2022-10-18 11:59
@sergeycherepanov Is this fixed for you?

**Comment by jakubmisek** [comment] 2022-10-25 10:39
@sergeycherepanov let's close this issue, shall we? You have also reported your issue as a review on https://open-vsx.org/extension/devsense/phptools-vscode/reviews

**Comment by jakubmisek** [comment] 2022-11-06 13:14
@sergeycherepanov can we close the issue? We're still waiting for more details on your issue report at https://open-vsx.org/extension/devsense/phptools-vscode/reviews

**Comment by sergeycherepanov** [comment] 2022-11-06 23:10
hi @jakubmisek!

Currently it looks like fixed. thanks!

**Comment by jakubmisek** [comment] 2022-11-06 23:12
@sergeycherepanov may I ask you to please close the issue at https://open-vsx.org/extension/devsense/phptools-vscode/reviews ?

**Comment by jakubmisek** [comment] 2022-12-02 14:11
Hi @sergeycherepanov - we still have the issue opened at https://open-vsx.org/extension/devsense/phptools-vscode/reviews - may I ask you to close it or update it

**Comment by Rabeya2019** [comment] 2022-12-08 14:05
![artisan](https://user-images.githubusercontent.com/52839921/206464901-ff79b07a-dc1b-43ac-b7f2-ad9afeed54e3.PNG)
Hey @jakubmisek i have an issue with PHP artisan serve.. this worked fine for me until last night ... for some reason my PHP artisan serve doesn't work. so as an alternative I  use the command shown in the screenshot, and there is an error.  I've been using the same command for months. this issue is new to me and I don't know how to fix it, haven't some across any solution to this.

also i noticed that sometimes maybe once or twice among numerous attempts, the error doesn't show up but suddenly my serve stops and error starts showing up again.

**Comment by jakubmisek** [comment] 2022-12-08 21:42
> ![artisan]Hey @jakubmisek i have an issue with PHP artisan serve.. this worked fine for me until last night ... for some reason my PHP artisan serve doesn't work. 

thank you for letting us know - working on the fix

**Comment by jakubmisek** [comment] 2022-12-08 21:43
@Rabeya2019 what version do you use? the release or pre-release? thank you

**Comment by Rabeya2019** [comment] 2022-12-08 23:18
> 

I use the released version

**Comment by jakubmisek** [comment] 2022-12-28 14:43
> Rabeya2019
this issue is caused by missing important Windows Updates - please run Windows Update to fix those.

**Comment by jakubmisek** [comment] 2022-12-28 14:44
@sergeycherepanov Sergey - you have reported **issue** on the **Ratings page** (https://open-vsx.org/extension/devsense/phptools-vscode/reviews) - if your issue is fixed now, REMOVE YOUR RATING there

**Comment by jakubmisek** [comment] 2023-01-10 14:53
@sergeycherepanov Sergey, we have an unresolved "rating" where you have reported that you have broken something.

![image](https://user-images.githubusercontent.com/842150/211583895-08f00878-3ac3-4e61-96cf-d5beb608819a.png)

May I ask to resolve the "rating"

**Comment by jakubmisek** [comment] 2023-01-30 13:32
@sergeycherepanov may I ask to update your issue report on https://open-vsx.org/extension/devsense/phptools-vscode/reviews?

thank you

**Comment by jakubmisek** [comment] 2023-02-08 17:44
@sergeycherepanov may I ask to update your review on https://open-vsx.org/extension/devsense/phptools-vscode/reviews ?

**Comment by jakubmisek** [comment] 2023-03-16 13:55
@sergeycherepanov this issue has been "reported" at https://open-vsx.org/extension/devsense/phptools-vscode/reviews - please update it as well. This is not a review.

**Comment by jakubmisek** [comment] 2023-03-27 20:51
@sergeycherepanov please update the issue on https://open-vsx.org/extension/devsense/phptools-vscode/reviews

**Comment by sergeycherepanov** [comment] 2023-04-09 01:30
@jakubmisek I revoked the review

**Comment by jakubmisek** [comment] 2023-04-09 12:52
thank you @sergeycherepanov

**Closed by jakubmisek** 2023-04-09 12:52 UTC
