### ISSUE TITLE
Extension keeps crashing (Mac)

### ISSUE THREAD

**Issue by svenax** [DEVSENSE/phptools-docs#42] opened 2019-08-22 07:41 UTC
The extension crashes constantly

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot open the file.
 (Exception from HRESULT: 0x80070004)
   at System.Xml.XmlCharType.InitInstance()
   at System.Xml.XmlCharType.get_Instance()
   at System.Xml.XmlTextReaderImpl..ctor(XmlNameTable nt)
   at System.Xml.XmlTextReaderImpl..ctor(String url, TextReader input, XmlNameTable nt)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at PHP.VisualStudio.Language.Nodes.Builtin.ManualNodes.LoadManualLibrary(Byte[] xmlcontent, String culture)
   at PHP.VisualStudio.Language.Nodes.Builtin.ManualNodes.GetManual(String culture)
   at Devsense.PHP.LanguageServer.Project.WorkspaceProject.PhpManualReferences.Devsense.PHP.Nodes.Providers.IProjectReferences.get_References()
   at PHP.VisualStudio.Language.Nodes.Project.ProjectContainer.QueryReferences()
   at PHP.VisualStudio.Language.Nodes.Project.ProjectContainer.EnsureReferences()
   at PHP.VisualStudio.Language.Nodes.Project.ProjectContainer.get_References()
   at PHP.VisualStudio.Language.Nodes.Project.ProjectTablesWithReferences.GetClass(QualifiedName qname)
   at Devsense.PHP.CodeSense.Completion.Implementation.NodeResolver.ResolveLocalNodes(INodesCollection tables, ICodeSenseNodeInfo info)
   at Devsense.PHP.CodeSense.Completion.Implementation.NodeResolver.ResolveNodes(INodesCollection tables, ICodeSenseNodeInfo info)
   at Devsense.LanguageServer.Utils.NodeUtils.ResolveSingleNode(ICodeSenseNodeInfo info, INodesCollection tables)
   at Devsense.LanguageServer.Utils.NodeUtils.ResolveNode(TextDocumentPositionParams position, ProjectContainer project, ICodeSenseNodeInfo& sourceNode, MatchMode mode)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.ProcessHover(Object requestId, TextDocumentPositionParams position)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.Run()
   at Devsense.PHP.LanguageServer.Program.Main(String[] args)
```
[crash.txt](https://github.com/DEVSENSE/phptools-docs/files/3528878/crash.txt)

**Comment by jakubmisek** [comment] 2019-08-22 11:18
Sorry for the troubles. May I ask you to run following on command line:
```
dotnet --version
```

**Comment by svenax** [comment] 2019-08-22 11:42
```
$ dotnet --version
2.2.103
```

**Comment by jakubmisek** [comment] 2019-08-22 12:09
Thank you, it seems 2.2.103 is not compatible with php tools.

To quickly fix this you can install the latest `.NET Core 2.2` (either Runtime or Sdk) on https://dotnet.microsoft.com/download .

We'll try to fix this within the next update.

**Comment by svenax** [comment] 2019-08-22 12:25
I still get exactly the same crash with version 2.2.401.

**Comment by jakubmisek** [comment] 2019-08-22 12:44
We'll try to fix this asap, I'll give you the setup package so you can test it. Thank you.

This is caused by some incompatibilities in .NET itself.

**Comment by jakubmisek** [comment] 2019-08-22 15:16
May I ask to try fllowing:

[phptools-vscode-1.0.3867.zip](https://github.com/DEVSENSE/phptools-docs/files/3530765/phptools-vscode-1.0.3867.zip)

1. Open VS Code
2. Bring the Command Palette
3. Run the command
4. Extensions: Install from VSIX
5. Navigate to the downloaded file

**Comment by svenax** [comment] 2019-08-22 15:33
I'm afraid it still crashes the same way.

**Comment by jakubmisek** [comment] 2019-08-22 15:45
Is it Linux OS ?

I usually don't recommend restarting, but `0x80070004` errors means "Cannot open file", indicating the DLL might being updated or locked by another process.

If you'd have time, may I ask to restart the PC ? Otherwise we'll keep looking for another solution,

Thank you

**Comment by svenax** [comment] 2019-08-22 15:49
MacOS as can be seen in the crash log attached to the first message. I did restart after updating DOTNet to the latest version. Don't have time to do it again now, but may try again tonight.

**Comment by jakubmisek** [comment] 2019-08-22 15:55
Thanks, overlooked that one, seems like restarting won't help. We'll try to prepare a working release.

**Comment by jakubmisek** [comment] 2019-09-05 11:55
The latest update - `1.0.3936` - should resolve *some* issues on Mac.

It does not depend on your `dotnet` runtime you have instead it has its own bundled avoiding similar issues.

**Comment by svenax** [comment] 2019-09-05 12:08
Great. If you add a link to the file I can have a try.

**Comment by jakubmisek** [comment] 2019-09-05 12:16
You can install right from the VSCode or at https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode .

Thank you! If the problem persists, we'll try to find another fix.,

**Comment by svenax** [comment] 2019-09-05 13:49
I'm sorry but when I activated the extension again I got a "License expired" message, so I can't do more testing right now.

**Comment by jakubmisek** [comment] 2019-09-05 15:59
Seems the latest update fixes the issue on mac os, closing the issue, and thank you Sven

**Closed by jakubmisek** 2019-09-05 15:59 UTC
