### ISSUE TITLE
How to disable premium?

### ISSUE THREAD

**Issue by mikeerickson** [DEVSENSE/phptools-docs#464] opened 2023-12-21 17:15 UTC
I recently tried the Premium version (using the trial key) and my Laravel code is getting mangled badly when I save (or format) 

For example, in a `web.php` file what starts like this

```
Route::view('/', 'welcome');;
```

Gets mangled to 

```
Symfony\Component\Routing\Routeny\Component\Routing\Attribute\Routeny\Component\Routing\Annotation\Routeinate\Routing\Route::view('/', 'welcome');
```

Or, in a simple seeder

```
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('transactions', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent();
```

becomes

```
return new class extends PHPUnit\TextUI\XmlConfiguration\Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Nette\Schema\Schema::create('transactions', function (Blueprint $table) {
   
```

This is just a small sampling of what is going haywire!

I am not able to find the offending setting, so my only recourse is to disable the plugin completely

Again, this just started happening after I enabled the PREMIUM version 

What is causing this?

I have tried to find help by using the DEVSENSE forum, but have not received a response (posted it a few days ago)

**Comment by jakubmisek** [comment] 2023-12-21 20:21
thank you for reporting this!

I think this is caused by setting in settings.json, namely the `"editor.codeActionsOnSave": {"source.fixAll":`

**Comment by jakubmisek** [comment] 2023-12-21 20:22
yep, confirmed -please disable the setting above for now, we'll fix it asap

**Comment by jakubmisek** [comment] 2023-12-21 22:19
fixed in the latest pre-release, 

we'll update the mail release soon.

**Closed by jakubmisek** 2023-12-21 22:19 UTC
