### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by Oscurlo** [DEVSENSE/phptools-docs#465] opened 2024-01-03 16:26 UTC
I tried using the extension but after a while it starts removing some of the code.
Also, if there are conditions or loops without brackets in parts of the code, it starts to identify everything that is wrong.

for example using "format document" several times in my small class

```PHP
<?php

namespace Config;

use Closure;
use PDO;

class CRUD extends ProcessData
{
    public Closure $create, $read, $update, $delete;
    public function __construct(?PDO $conn = null)
    {
        parent::__construct($conn);
        $this->create = fn (String $table, array $data): array => $this->prepare($table, $data)->insert();
        $this->read   = fn (String $table, String $condition = "1 = 1", array $prepare = []): mixed => $this->conn->executeQuery("SELECT * FROM {$table} WHERE {$condition}", $prepare);
        $this->update = fn (String $table, array $data, String $condition): array => $this->prepare($table, $data)->update($condition);
        $this->delete = fn (): String => "coming soon ¯\_(ツ)_/¯";
    }
}

```

**Comment by Miloslav** [comment] 2024-01-05 14:07
I can't reproduce this. Do you have any other extension installed?

**Comment by Miloslav** [comment] 2024-01-10 11:36
Thank you. I don't see anything that might interfere with the PHP extension in the list.

Please try again and let me know. If that appears, please provide me with the resulting code which has been altered incorrectly.

**Comment by Miloslav** [comment] 2024-01-23 09:36
I'm closing this one since we cannot replicate it. If the problem reoccurs, please open a new issue.

Thank you

**Closed by Miloslav** 2024-01-23 09:36 UTC
