### ISSUE TITLE
VSC

### ISSUE THREAD

**Issue by Mordef** [DEVSENSE/phptools-docs#2] opened 2018-10-18 11:38 UTC
when write this:
preg_match_all('/\{\d+\}/',)

now it crashed, because i don't continue finished the function it crashes more then 5 times and will not restart.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Devsense.PHP.ControlFlow.Analysis.Visitors.ExpressionAnalysisVisitor.VisitCallSignature(CallSignature callsig)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.TablesAnalysisVisitor.HandleFunctionCall(QualifiedName name, Nullable`1 fallbackname, Span span, CallSignature callsignature)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.TablesAnalysisVisitor.HandleFunctionCall(DirectFcnCall fcn)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.ExpressionAnalysisVisitor.VisitDirectFcnCall(DirectFcnCall x, ConditionBranch branch)
   at Devsense.PHP.ControlFlow.Graph.GraphVisitor.VisitCFGBlockStatements(Block x)
   at Devsense.PHP.ControlFlow.Graph.GraphVisitor.VisitCFGBlockInternal(Block x)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.AnalysisVisitor.VisitCFG(ControlFlowGraph x)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.ExpressionAnalysisVisitor.VisitCFG(ControlFlowGraph x)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.TablesAnalysisVisitor.VisitCFG(ControlFlowGraph x)
   at Devsense.PHP.ControlFlow.Analysis.Visitors.CheckAnalysisVisitor.VisitCFG(ControlFlowGraph x)
   at Devsense.PHP.ControlFlow.Analysis.State.AnalyseCfg(ControlFlowGraph cfg, LambdaFunctionExprHandler handleLambdaExpr, IRoutine routine, CallInfo call, LocalsState callState, ITables tables, ErrorAnalysisSettings errSettings)
   at PHP.VisualStudio.Language.Nodes.Project.ProjectAnalysis.AnalyseRoutine(IRoutine routine, CallInfo call, LocalsState callState)
   at PHP.VisualStudio.Language.Nodes.Project.ProjectAnalysis.EnsureRoutineAnalysed(IRoutine routine)
   at PHP.VisualStudio.Language.Nodes.Project.ProjectAnalysis.AnalyseNodeNoLock(GlobalCodeNode node)
   at PHP.VisualStudio.Language.Nodes.Project.ProjectAnalysis.AnalyseNode(GlobalCodeNode node)
   at Devsense.PHP.LanguageServer.Project.WorkspaceProject.<.ctor>b__11_0(Object o) in C:\agent\_work\10\s\src\Devsense.PHP.LanguageServer\Project\WorkspaceProject.cs:line 80
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
[Error - 1:33:35 PM] Connection to server got closed. Server will not be restarted.

**Comment by Mordef** [comment] 2018-10-18 11:44
Looks like, evry time, i start a function and to slow for all arguments, the server crashed.
Last crash:
str_replace("", .... crash

**Comment by jakubmisek** [comment] 2018-10-18 11:46
this is a duplicate of #1 

should be fixed in 1.0.2839 https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode ?

**Comment by jakubmisek** [comment] 2018-10-18 12:46
fixing other related issues, will be updated in few minutes

**Comment by jakubmisek** [comment] 2018-10-18 13:12
release 1.0.2839 fixes the issue, please report a new issue if it happens again

**Closed by jakubmisek** 2018-10-18 13:12 UTC
