### ISSUE TITLE
The remote debug console outputs some error logs.

### ISSUE THREAD

**Issue by tiansin** [DEVSENSE/phptools-docs#39] opened 2019-08-02 10:48 UTC
```
{ XdebugError: command is not available
    at new ft (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:1169)
    at Mt.<anonymous> (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:9579)
    at Generator.next (<anonymous>)
    at o (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:208) code: 5, name: 'XdebugError' }
Error applying XdebugSettings: command is not available
Error applying XdebugSettings: command is not available
{ XdebugError: command is not available
    at new ft (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:1169)
    at new _t (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:3651)
    at Mt.<anonymous> (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:9329)
    at Generator.next (<anonymous>)
    at o (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:208) code: 5, name: 'XdebugError' }
{ XdebugError: command is not available
    at new ft (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:1169)
    at new _t (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:3651)
    at Mt.<anonymous> (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:9329)
    at Generator.next (<anonymous>)
    at o (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:208) code: 5, name: 'XdebugError' }
{ XdebugError: command is not available
    at new ft (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:1169)
    at new _t (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:3651)
    at Mt.<anonymous> (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:9329)
    at Generator.next (<anonymous>)
    at o (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:208) code: 5, name: 'XdebugError' }
{ XdebugError: command is not available
    at new ft (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:1169)
    at new _t (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:3651)
    at Mt.<anonymous> (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:9329)
    at Generator.next (<anonymous>)
    at o (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/connection.js:1:208) code: 5, name: 'XdebugError' }
Error applying XdebugSettings: command is not available
Error applying XdebugSettings: command is not available
Error applying XdebugSettings: command is not available
```

**Comment by tiansin** [comment] 2019-08-05 15:00
{
            "name": "Remote for xDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "/www/admin3" : "${workspaceRoot}"
            }
        }

**Comment by Miloslav** [comment] 2019-08-13 09:19
Hi,

I've tried this settings, but couldn't replicate. 

What PHP and Xdebug version do you have?

Thanks!

**Comment by Miloslav** [comment] 2019-08-19 10:24
Hi tisian,

Did this happen again?

Thank you

**Comment by tiansin** [comment] 2019-08-20 09:44
@Miloslav Always appear when debugging remotely.

**Comment by Miloslav** [comment] 2019-08-20 10:00
@tiansin I see, could you please check what PHP and Xdebug version is present on the remote server? I will try to recreate it.

**Comment by tiansin** [comment] 2019-08-20 12:13
@Miloslav After clicking Stop Debugging, the port is still occupied. You must close the vscode to release the port.

`{ Error: listen EADDRINUSE :::9000
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1421:7)
    at launchRequest.Promise (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/debugger.js:1:6315)
    at new Promise (<anonymous>)
    at c (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/debugger.js:1:4942)
    at ei.<anonymous> (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/debugger.js:1:6373)
    at Generator.next (<anonymous>)
    at e (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/debugger.js:1:375)
    at new Promise (<anonymous>)
    at e (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/debugger.js:1:152)
    at ei.launchRequest (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/debugger.js:1:2557)
    at ei.dispatchRequest (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-debugadapter/src/debugSession.ts:442:10)
    at ei.dispatchRequest (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/out/src/debug/debugger.js:1:8701)
    at ei._handleData (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-debugadapter/src/protocol.ts:130:14)
    at Socket.start.inStream.on (/Users/lover/.vscode/extensions/devsense.phptools-vscode-1.0.3774/node_modules/vscode-debugadapter/src/protocol.ts:30:46)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 9000 }`

**Comment by tiansin** [comment] 2019-08-20 12:15
Local:

> PHP 7.1.23 (cli) (built: Nov 27 2018 16:59:25) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
>     with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans

Remote:

> PHP 7.2.12 (cli) (built: Nov 30 2018 17:31:59) ( NTS )
> Copyright (c) 1997-2018 The PHP Group
> Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
>     with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans

Command:
`autossh -M 5555 -NR 9001:127.0.0.1:9000 root@xxx.xxx.xx.xx`

**Comment by tiansin** [comment] 2019-08-20 12:47
@Miloslav  I didn't do any mouse and keyboard operations in the whole process of the animation, and always automatically run after the breakpoint.
![1](https://user-images.githubusercontent.com/4232281/63348346-a3f31c80-c38b-11e9-9190-7e3805708fb9.gif)

**Comment by tiansin** [comment] 2019-08-20 13:13
@Miloslav  Is this error related to the problem I submitted earlier?I noticed that there is the word 'XdebugSettings'.

`XdebugSettings: command is not available Error applying XdebugSettings: command is not available`

https://github.com/DEVSENSE/phptools-docs/issues/36#issuecomment-515216122

**Comment by jakubmisek** [comment] 2019-09-05 09:09
@tiansin 

```
Error: listen EADDRINUSE :::9000
```

means that there is already debugger listening on port `9000`.  Usually another VSCode is running and debugging remotely? 

Another option is VSCode didn't close the socket from the previous remote debugging session @Miloslav ?

**Comment by jakubmisek** [comment] 2019-11-04 15:20
In general caused by running two debugging at once, closing for now. Please comment if you'd have anything to add :)

**Closed by jakubmisek** 2019-11-04 15:20 UTC
