### ISSUE TITLE
No classes are found

### ISSUE THREAD

**Issue by svenax** [DEVSENSE/phptools-docs#45] opened 2019-09-05 14:56 UTC
macOS: 10.14.6
phptools: 1.0.3936

In a fairly complex project using the Zend Framework 2 module structure, the Problems log fills up with thousands of "Use of unknown class" messages. Is phptools perhaps depending on the Composer autoloader to find classes? I would have expected it to build it's own dependency database.

**Comment by jakubmisek** [comment] 2019-09-05 16:01
PHP Tools reads all the classes within the workspace. There might be a bug and problems are reported BEFORE we read all the files, or composer packages are not restored?

**Comment by svenax** [comment] 2019-09-05 16:26
I get almost 3000 "Use of unknown class" warnings, and maybe 5 other messages in the Problems console. Nothing is logged in the Language server console. I mentioned Composer only because ZF2 does *not* use it, but rather its own fairly complex class loader. But that should not matter since phptools is not using it anyways.

**Comment by jakubmisek** [comment] 2019-09-05 16:29
isn't it possible files containing the classes are excluded using `files.exclude` setting?

**Comment by svenax** [comment] 2019-09-05 16:33
No, it is my own code that is not recognised.

**Comment by jakubmisek** [comment] 2019-09-07 15:16
For now, I would recommend to disable workspace analysis (https://github.com/DEVSENSE/phptools-docs/issues/29)

In workspace settings or in `settings.json`, put following:
```json
{
    "php.problems.workspaceAnalysis": false
}
```

This should speed up workspace loading, and you'll still see problems in opened documents.

**Comment by svenax** [comment] 2019-09-09 13:08
PHP Tools is not usable for me until it can reliably analyse the entire workspace. I'm reverting to using *PHP IntelliSense* for the time being.

**Comment by jakubmisek** [comment] 2019-09-09 13:12
I understand,

As mentioned, you can disable the background analysis in your settings.json (https://github.com/DEVSENSE/phptools-docs/issues/45#issuecomment-529117019) so it does nothing on background like the other extensions do
```json
{
    "php.problems.workspaceAnalysis": false
}
```

Also recommending to exclude problems reporting in /vendor folder

```json
{
    "php.problems.exclude": {
        "vendor": true
    },
}
```

I hope it helps.

**Comment by addshore** [comment] 2020-06-30 20:26
It looks like I encountered a similar issue with tens of thousands of issues being reported.

Adding "php.problems.workspaceAnalysis": false to my settings emptied out this list but problems remained in the file that I have open.

A concrete example would be this wfDebugLog global function:
![image](https://user-images.githubusercontent.com/3308769/86172965-1b9ae780-bb17-11ea-9ca6-6c41866b47e0.png)
This is included in the file `includes/GlobalFunctions.php` in my workspace and I'm encountering the error in `extensions/Wikibase/lib/includes/Store/Sql/Terms/Util/ReplicaMasterAwareRecordIdsAcquirer.php`

I also had this issue with a few classes, but managed to make those issues disappear by opening the files that the classes were defined in. That doesn't appear to work for the global function.

Seemingly cuting and pasting the content of the whole file seemed to make all of these false-positive problems go away (a trick I have used with phpstorm in the past when it messes something up).
Not sure if any of these rambling helps improve the situation at all :)

**Comment by jakubmisek** [comment] 2020-06-30 22:19
Seems some files (or all of them) may not be scanned upon startup causing the issues above. Thank you for all the hints, we'll be working on it.

**Comment by addshore** [comment] 2020-07-01 09:10
If you want any debugging help / if I can provide any logs etc just give me a poke!

**Comment by jakubmisek** [comment] 2020-07-05 14:23
@addshore we have tried to replicate the issue in several ways but not succeeded.

May I ask you for more details;

- how did you open the project? Was it simply `File / Open Folder` ?
- Linux or Win?
- what is the path to your project? is it on the local disk drive?
- any issues listed in OUTPUT panel, tab "PHP Language Server" (screenshot below)?

![image](https://user-images.githubusercontent.com/842150/86534781-86fc0500-bedb-11ea-9520-4e6af2ef5cdc.png)

- anything specific in your settings.json, like an additional `"files.exclude"`?

![image](https://user-images.githubusercontent.com/842150/86534820-d4787200-bedb-11ea-83cb-a4451240ba52.png)

Thank you!

**Comment by addshore** [comment] 2020-07-08 09:09
So I am running with vscode on Windows but connecting to WSL, so all of my code is there.
I'm running with MediaWiki core and also a collection of extensions.

```
adam@adsh+wsl:~/dev/git/gerrit/mediawiki/core/extensions (master)$ $ ls
3D                  Citoid                 ExtensionDistributor  JsonConfig                  Newsletter           README                 TorBlock                   WikibaseLexeme
AbuseFilter         CodeEditor             FeaturedFeeds         JsonData                    Nuke                 ReadingLists           Translate                  WikibaseLexemeCirrusSearch
AdvancedSearch      CodeMirror             FileExporter          Kartographer                OATHAuth             Renameuser             TranslateSvg               WikibaseManifest
AntiSpoof           Cognate                FileImporter          LabeledSectionTransclusion  OAuth                RevisionSlider         TranslationNotifications   WikibaseMediaInfo
ApiFeatureUsage     Collection             FlaggedRevs           Linter                      OAuthAuthentication  Score                  Transliterator             WikibaseMobile
ApprovedRevs        CommonsMetadata        Flow                  LocalisationUpdate          ORES                 Scribunto              TrustedXFF                 WikibaseQualityConstraints
ArticlePlaceholder  ConfirmAccount         Gadgets               LoginNotify                 OggHandler           SecureLinkFixer        TwoColConflict             Wikidata.org
Babel               ConfirmEdit            GeoData               Mailgun                     OpenID               SecurePoll             TwoFactorAuthentication    WikidataEntitySuggester
BetaFeatures        Contributors           GlobalBlocking        Maps                        OpenIDConnect        SiteMatrix             UniversalLanguageSelector  WikidataPageBanner
BoilerPlate         ContributorsAddon      GlobalCssJs           MassAction                  PageImages           SpamBlacklist          UrlShortener               WikimediaBadges
BounceHandler       DeleteBatch            GlobalPreferences     MassMessage                 PageViewInfo         SyntaxHighlight_GeSHi  UserMerge                  WikimediaEditorTasks
Campaigns           Disambiguator          GlobalUsage           MassMessageEmail            PagedTiffHandler     SyntaxHighlighter      VipsScaler                 WikimediaEvents
Capiunto            DiscussionTools        GlobalUserPage        Math                        ParserFunctions      TemplateData           VisualEditor               WikimediaMessages
CategoryTree        DismissableSiteNotice  Graph                 MathSearch                  ParserHooks          TemplateInfo           WSOAuth                    WikimediaPageViewInfo
CentralAuth         Echo                   GraphViz              MediaModeration             PdfHandler           TemplateSandbox        WebAuthn                   WikimediaShopLink
CentralNotice       Elastica               GuidedTour            MobileApp                   PluggableAuth        TemplateStyles         WikiEditor                 Wikisource
CharInsert          ElectronPdfService     ImageLink             MobileFrontend              PluggableSSO         TemplateWizard         WikiLexicalData            XAnalytics
CheckUser           EntitySchema           ImageMap              MoveToCommons               Poem                 TextExtracts           WikiLove                   cldr
CirrusSearch        EventBus               Interwiki             MoveToCommonsClient         PoolCounter          Thanks                 Wikibase                   examples
Cite                EventLogging           InterwikiMap          MultimediaViewer            ProofreadPage        TimedMediaHandler      WikibaseCirrusSearch       timeline
CiteThisPage        EventStreamConfig      InterwikiSorting      NavigationTiming            PropertySuggester    TitleBlacklist         WikibaseImport             wikihiero
```

I ran vscode by running `code .` in WSL, which I imagine is the equivalent of just opening the project directory.

> what is the path to your project? is it on the local disk drive?

In the WSL context, the path is local and at `~/dev/git/gerrit/mediawiki/core`.

I just turned `workspaceAnalysis` back on for a second to have a look around and see how it is performing now.

![image](https://user-images.githubusercontent.com/3308769/86899909-85605600-c102-11ea-99d5-fb090d2f98b3.png)

The OUTPUT panel for the language server shows the following:

```
PHP Tools server started.
    Path: /home/adam/.vscode-server/extensions/devsense.phptools-vscode-1.0.4698/out/server/Devsense.PHP.LanguageServer.dll
    PID: 5151
    Processing files: .php; .php5
```

No errors, but also no output, should there be any?
Is it possible that for such a large project it just needs lots more time to process?

I have nothing in my `files.exclude` (other than the defaults)
![image](https://user-images.githubusercontent.com/3308769/86900093-ceb0a580-c102-11ea-85d3-a76cac5ac8aa.png)

I'll leave it running for a bit and see if anything changes, but I don't see any processes seeming to do much.
```
adam@adsh+wsl:~/dev/git/gerrit/mediawiki/core/extensions (master)$ $ ps 5151
  PID TTY      STAT   TIME COMMAND
 5151 pts/1    Sl+    1:12 /home/adam/.vscode-server/extensions/devsense.phptools-vscode-1.0.4698/out/server/Devsense.PHP.LanguageServer
```

**Comment by jakubmisek** [comment] 2020-07-11 12:02
@addshore nice, thank you very much, we'll be processing it for a while.

The first possible issue on our side might be the lack of support for UNC paths and remote paths, but since you have 31K+ problems found, it'll be probably something else..

**Comment by addshore** [comment] 2020-07-14 15:22
Is there any way I can turn on more verbose output and perhaps get you all some more hints?
Or have you managed to reproduce the issue as I described? :)

**Comment by addshore** [comment] 2020-07-16 10:57
Another few days on and I now only have 5k reported errors with workspace analysis turned on

![image](https://user-images.githubusercontent.com/3308769/87663165-4f068480-c75b-11ea-9b40-07c454711ba8.png)

And every time I open one of these files that vscode thinks is missing it will then realize that it is there and those problems go away!

Is there a way to make phptools reload every file in a workspace?

**Comment by jakubmisek** [comment] 2020-07-16 11:01
@addshore thanks for the update. The last version improved the analysis, so a lot of falsely reported problems went away.

PhpTools suppose to load and analyze all the files in the workspace, so it is an obvious bug and we're trying to fix it :/ we have a few hints, I hope the next update makes it another step better

**Comment by addshore** [comment] 2020-07-20 12:46
So I spotted that I got another update today:

`Downloading PHP Tools dependencies (linux-x64-1.0.4934) ...`

And now it is only reporting 3k errors for me with workspace analysis on:

![image](https://user-images.githubusercontent.com/3308769/87939064-61e8c400-ca8f-11ea-947e-486555cffcea.png)

Seems like yours making some great progress

**Comment by jakubmisek** [comment] 2020-07-20 19:42
Yes, thank you for noticing and for the feedback. 

1.0.4934 (July 19, 2020) updates analysis so it does not report some of the false problems. It also improves editing and initial workspace loading, but we're still working on it.

Please if you have a piece of code with a wrong problem reported, we'd be happy for an issue.

**Comment by addshore** [comment] 2020-07-20 23:09
As I have been browsing around it has gone back up to 7k+ problems.

Most of these seem to be "Use of unknown class", for example:
![image](https://user-images.githubusercontent.com/3308769/87994922-0b5aa480-cae6-11ea-8e32-3f60c646a5b0.png)
Also "Call to unknown function"
![image](https://user-images.githubusercontent.com/3308769/87994994-33e29e80-cae6-11ea-8e1e-034ddc6b838e.png)
and also unknown constants

**Comment by jakubmisek** [comment] 2020-07-21 09:07
@addshore I guess those classes/functions actually exist in the workspace :)

**Comment by addshore** [comment] 2020-07-21 16:13
> @addshore I guess those classes/functions actually exist in the workspace :)

Yes

> If you search for them using `Ctrl+P`, does the editor find them?

No :/
"No Matching Workspace Symbols"

And as mentioned before, the moment I open each of these files that contains the class the problems go away.
But needing to do that for the hundreds or thousands of files is not an ideal solution :/

**Comment by jakubmisek** [comment] 2020-07-28 12:33
May I ask what you have in **Settings / files.exclude**:
![image](https://user-images.githubusercontent.com/842150/88663256-938b0c00-d0db-11ea-9869-45a6286dde1c.png)

---

@addshore we have released an update which logs most of the unexpected failures during workspace load. You can find it in Output panel, "PHP Language Server" group:
![image](https://user-images.githubusercontent.com/842150/88663858-7efb4380-d0dc-11ea-9b27-2233da1046ba.png)

**Comment by addshore** [comment] 2020-07-29 10:34
```
PHP Tools server started.
    Path: /home/adam/.vscode-server/extensions/devsense.phptools-vscode-1.0.4962/out/server/Devsense.PHP.LanguageServer.dll
    PID: 14268
    Processing files: .php; .php5

Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/Elastica/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/CodeEditor/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/GuidedTour/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/DeleteBatch/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/DiscussionTools/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/NavigationTiming/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/CentralAuth/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/Graph/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/WikimediaPageViewInfo/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/WikibaseLexemeCirrusSearch/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/TextExtracts/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/Citoid/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/WikimediaShopLink/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/CentralNotice/.git' is excluded.
Directory '/home/adam/dev/git/gerrit/mediawiki/core/extensions/UniversalLanguageSelector/.git' is excluded.
Too many open files at EnumeratePhpFilesInFolder
Too many open files at EnumeratePhpFilesInFolder
Too many open files at EnumeratePhpFilesInFolder
Too many open files at EnumeratePhpFilesInFolder
```

That last message continues quite a lot...

My files.exclude is default afaik

![image](https://user-images.githubusercontent.com/3308769/88790087-8596c300-d18f-11ea-992e-32aa7c6efca5.png)

**Comment by jakubmisek** [comment] 2020-07-29 10:52
excellent! thank you, `Too many open files` seems to be the clue!

**Comment by jakubmisek** [comment] 2020-07-29 13:59
Just released an update that should fix the issue. Any feedback would be appreciated :)

**Comment by jakubmisek** [comment] 2020-08-04 12:16
Does the workspace load normally now? We are currently working on "problems analysis", trying to not report redundant or falsely detected problems in general.

**Comment by addshore** [comment] 2020-08-05 12:56
I havn't seem any classes etc that I know to exist report as missing in the last days, so I think this bit is now correct for me.

**Comment by jakubmisek** [comment] 2020-08-05 12:58
@addshore awesome, so now we have tons of "problems" reported and we have to deal with them. I'm closing this issue, and please let's open a new one where we can discuss specific code fragments reported as a warning?

**Closed by jakubmisek** 2020-08-05 12:58 UTC
Labels: bug
