### ISSUE TITLE
No quickfix option in phpdoc for unknown interface, when the interface is known to exist under a namespace (PHP0413)

### ISSUE THREAD

**Issue by addshore** [DEVSENSE/phptools-docs#70] opened 2020-08-10 13:56 UTC
While looking around at some reported issues I found a valid issue that I wanted to fix.
When fixing I noticed that perhaps a bit of functionality is missing.

When making the change below in MediaWiki which switches from the overly specific `LoadBalancer` class to the `ILoadBalancer` interface instead in a phpdoc annotation phptools correctly stated that the class doesn't exist.

```
adam@adsh+wsl:~/dev/git/gerrit/mediawiki/core (master)$ $ git diff
diff --git a/includes/watcheditem/WatchedItemStore.php b/includes/watcheditem/WatchedItemStore.php
index 091f3ca757..1ae7b6ce9a 100644
--- a/includes/watcheditem/WatchedItemStore.php
+++ b/includes/watcheditem/WatchedItemStore.php
@@ -40,7 +40,7 @@ class WatchedItemStore implements WatchedItemStoreInterface, StatsdAwareInterfac
        private $lbFactory;

        /**
-        * @var LoadBalancer
+        * @var ILoadBalancer
         */
        private $loadBalancer;
```

![image](https://user-images.githubusercontent.com/3308769/89789824-07d0a100-db19-11ea-8571-abd8e9780549.png)

However, it didn't suggest the quick fix of adding a use statement for the class

```use Wikimedia\Rdbms\ILoadBalancer;```

phptools knew about and had indexed ILoadBalancer and I would have expected this quickfix to be an option.

**Comment by jakubmisek** [comment] 2020-08-10 21:45
you're right, the quick fix is missing in case the issue is in phpdoc

**Comment by jakubmisek** [comment] 2020-08-11 11:18
fixed within the next update, thanks!

**Closed by jakubmisek** 2020-08-11 11:18 UTC
