### ISSUE TITLE
When implemeting an interface with enums I got red highlightings

### ISSUE THREAD

**Issue by jquirogaa** [DEVSENSE/phptools-docs#307] opened 2023-03-09 18:15 UTC
![image](https://user-images.githubusercontent.com/95649309/224118453-a9d74014-b5fb-4dfb-bbf5-3ae18c401f8c.png)

I think it does not support it

**Comment by jakubmisek** [comment] 2023-03-09 18:55
Hi @jquirogaa 

Those errors do not look like they're from our extension.

May I ask you to check if it's not caused by another extension?

**Comment by jakubmisek** [comment] 2023-03-13 14:58
The red highlightings are not caused by our extension.

Closing.

Please let us know if there would be anything else we can help with.

**Closed by jakubmisek** 2023-03-13 14:58 UTC

**Comment by jquirogaa** [comment] 2023-03-13 16:20
I am using this DEVSENSE extension
![image](https://user-images.githubusercontent.com/95649309/224762997-12d28da3-f2d5-4404-baa1-d82b54268588.png)

**Comment by jakubmisek** [comment] 2023-03-13 20:03
Isn't there any other extension installed? Our extension cannot output errors like `"'{' expected"`.

**Comment by jquirogaa** [comment] 2023-03-13 20:23
You're right! PHP Debug extension was causing these falsy errors, thanks
![image](https://user-images.githubusercontent.com/95649309/224823722-835873c5-b470-4da8-bce8-d302b1d6419b.png)

**Comment by jakubmisek** [comment] 2023-03-13 20:43
@jquirogaa great you found it! thank you for the update, I'm glad it was resolved)
