### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by maakfischer** [DEVSENSE/phptools-docs#318] opened 2023-04-05 09:35 UTC
I keep getting the following **errors**:
```
Couldn't start language server for 'darwin-x64' on 'darwin-x64'. Have you installed the extension correctly?
```
and
```
The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

The output of **VSCode (Version 1.77, running on Mac OS Ventura)** shows the following:
```
Internal Error, please report it to https://github.com/devsense/phptools-docs/issues 
MakeException, src[/\\]main[/\\]node_modules[/\\]node-sass[/\\]src[/\\]libsass[/\\].*[/\\]sassc++, 82, NestedQuantifiersNotParenthesized, +
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String, RegexOptions, CultureInfo)
   at System.Text.RegularExpressions.Regex.Init(String, RegexOptions, TimeSpan, CultureInfo& )
   at System.Text.RegularExpressions.Regex..ctor(String, RegexOptions, TimeSpan, CultureInfo)
   at System.Text.RegularExpressions.Regex..ctor(String , RegexOptions)
   at Devsense.LanguageServer.Utils.PathUtils.GlobToRegex(String glob)
   at Devsense.LanguageServer.Utils.PathUtils.GlobToPredicate(String glob)
   at Devsense.PHP.LanguageServer.Project.WorkspaceConventions.SetProblemsSelector(String glob, Predicate`1 predicate)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.<ProcessProblemsExcludeOption>b__69_1(JsonProperty p)
   at Devsense.PHP.Syntax.CollectionUtils.Foreach[T](IEnumerable`1 enumerable, Action`1 action)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.ProcessProblemsExcludeOption(JsonElement excludes)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.ProcessOptions(JsonElement opts)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.Initialize(InitializeParams initializeParams)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.PollAsync()
   at Devsense.PHP.LanguageServer.PhpLanguageServer.Devsense.PHP.LSP.Threading.IWorker.NextAsync()
   at Devsense.PHP.LanguageServer.Threading.WorkerFactoryExtensions.RunAsync(IWorker worker, CancellationToken cancellation)
   at Devsense.PHP.LanguageServer.Program.Main(String[] args)
Unhandled exception. System.Text.RegularExpressions.RegexParseException: MakeException, src[/\\]main[/\\]node_modules[/\\]node-sass[/\\]src[/\\]libsass[/\\].*[/\\]sassc++, 82, NestedQuantifiersNotParenthesized, +
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String, RegexOptions, CultureInfo)
   at System.Text.RegularExpressions.Regex.Init(String, RegexOptions, TimeSpan, CultureInfo& )
   at System.Text.RegularExpressions.Regex..ctor(String, RegexOptions, TimeSpan, CultureInfo)
   at System.Text.RegularExpressions.Regex..ctor(String , RegexOptions)
   at Devsense.LanguageServer.Utils.PathUtils.GlobToRegex(String glob)
   at Devsense.LanguageServer.Utils.PathUtils.GlobToPredicate(String glob)
   at Devsense.PHP.LanguageServer.Project.WorkspaceConventions.SetProblemsSelector(String glob, Predicate`1 predicate)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.<ProcessProblemsExcludeOption>b__69_1(JsonProperty p)
   at Devsense.PHP.Syntax.CollectionUtils.Foreach[T](IEnumerable`1 enumerable, Action`1 action)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.ProcessProblemsExcludeOption(JsonElement excludes)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.ProcessOptions(JsonElement opts)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.Initialize(InitializeParams initializeParams)
   at Devsense.PHP.LanguageServer.PhpLanguageServer.PollAsync()
   at Devsense.PHP.LanguageServer.PhpLanguageServer.Devsense.PHP.LSP.Threading.IWorker.NextAsync()
   at Devsense.PHP.LanguageServer.Threading.WorkerFactoryExtensions.RunAsync(IWorker worker, CancellationToken cancellation)
   at Devsense.PHP.LanguageServer.Program.Main(String[] args)
   at Devsense.PHP.LanguageServer.Program.<Main>(String[] args)
[Error - 11:14:58] Connection to server got closed. Server will not be restarted.
```

VSCode's **extension bisect** did not help.

best.wishes:maak.

**Comment by maakfischer** [comment] 2023-04-05 13:11
I just found out, that it has something to do with the provided PHP version in the VSCode settings, like here:
```
[…]

    "php.executablePath": "/usr/local/opt/php@8.0/bin/php",
    "php.debug.executablePath": "/usr/local/opt/php@8.0/bin/php",
    "php.problems.excludeGitIgnore": true,
    "php.executables": {
        "v8.0": "/usr/local/opt/php@8.0/bin/php",
    },

[…]
```

If I comment out the above lines, it works… as time comes by, I will further investigate.

**Comment by jakubmisek** [comment] 2023-04-05 14:34
@maakfischer thank you very much for reporting this and provided solution! Will be fixed.

**Comment by jakubmisek** [comment] 2023-04-05 15:24
@maakfischer The issue is in incorrectly formatted regular expression in the setting `"php.problems.exclude"`. We'll fix it so it won't crash!

**Closed** 2023-04-05 15:32 UTC
