### ISSUE TITLE
The debug console string is truncated.

### ISSUE THREAD

**Issue by tiansin** [DEVSENSE/phptools-docs#36] opened 2019-07-25 16:00 UTC
{
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "xdebugSettings": {
                "max_children": 128,
                "max_data": 40960,
            }
        }

@jakubmisek  The ‘max_data’ setting of 40960 seems to be invalid, and the string is still truncated by 1024.

**Comment by jakubmisek** [comment] 2019-07-25 20:21
Hi, PHP Tools do not have `xdebugSettings` settings (this probably comes from another extension). VS Code should underline those lines as they are invalid.

The full settings can be found on https://docs.devsense.com/en/vscode/debug/launch-json#remote-application-attach

For debug watch and locals, PHP Tools subsequently reads the full text (no setting needed). We'll take a look if we do the full data read in the debug console as well (cc @Miloslav).

**Comment by tiansin** [comment] 2019-07-25 21:11
@jakubmisek I have reason to believe that this is not brought about by other extensions.
![2](https://user-images.githubusercontent.com/4232281/61909032-b54f3180-af63-11e9-9744-fd3ee7dcd323.gif)

**Comment by jakubmisek** [comment] 2019-07-25 21:26
I see! Sorry for that, this setting is not needed for PHP Tools.

**Comment by tiansin** [comment] 2019-07-25 22:06
@jakubmisek The debug console output string has been truncated, the maximum length is only 1024 characters, which is certainly not enough. I can't adjust it now. The 'php-debug' extension is able to expand the output with 'max_data'. Rushing.

**Comment by jakubmisek** [comment] 2019-07-25 22:08
you are right, the issue is still open and it will be implemented in the next working day :) (it is 1am now ;))

**Comment by tiansin** [comment] 2019-07-29 09:26
@jakubmisek updating?

**Comment by jakubmisek** [comment] 2019-07-29 20:54
@tiansin working on it, thank you

**Comment by jakubmisek** [comment] 2019-08-16 16:05
This should get improved in `1.0.3774` (July 2019)

**Comment by jakubmisek** [comment] 2019-09-05 09:11
can we close this issue? we are preparing the new release and this issue seems to be resolved.

**Closed** 2019-11-04 15:20 UTC
